apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: web
      protocol: TCP
    - port: 53
      nodePort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      nodePort: 53
      name: dns-udp
      protocol: UDP
  selector:
    app: pihole

