apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: web
      protocol: TCP
    - port: 53
      nodePort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      nodePort: 53
      name: dns-udp
      protocol: UDP
  selector:
    app: pihole
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole-statefulset
  labels:
    app: pihole
spec:
  serviceName: pihole-service
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:v5.8.1
          env:
            - name: TZ
              value: Europe/London
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: pihole
              mountPath: /etc/pihole
            - name: dnsmasq
              mountPath: /etc/dnsmasq.d
  volumeClaimTemplates:
    - metadata:
        name: pihole
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: dnsmasq
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 50Mi
